### ISSUE TITLE
Implement version recognition

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgemagic-firmware#44]
A mobile app should be able to recognize the version of the firmware on the hardware and provide the option to update the firmware.

**Comment by kienvo** [comment]
It's already implemented in Device Information Profile: https://github.com/fossasia/badgemagic-firmware/blob/f5874d607315ff88b27414299089b8528b5bb07c/src/ble/profile/devinfo.c#L14-L15

The app should read the firmware version string by reading the value of the Firmware Revision String Characteristic (0x2A26) in the Device Information Profile (0x18A). This will be documented soon, along with the firmware versioning.

**Comment by mariobehling** [comment]
Ok, good. When you document this please reference this issue.

**Comment by froscon2024** [comment]
What does the preinstalled closed source firmware answer when you read out those values? 
Does it even have a version?

**Comment by kienvo** [comment]
> What does the preinstalled closed source firmware answer when you read out those values? Does it even have a version?

They left it default as the example in the EVT package: 'Firmware Revision'. Not just that characteristic but the whole 0x180A Service was left default. I think they don't have any reason to put more effort into this.

**Comment by froscon2024** [comment]
So its easy detectable with for example the android app if its closed source or the opensource firmware because none of the foss releases from fossasia would let it default like the closed source one did.
Yes, i know that the foss version looks different on the badge, but the desktop or android software that read out the firmware should also be able to know without the need of the user to choose which one is installed.
